version: '3.7'

services:
    app:
      build: ./
      container_name: tex2vec-api
      entrypoint: [ '/bin/sh', '-c' ]
      restart: always
      command:
        - /opt/app/.venv/bin/uvicorn app:app --host 0.0.0.0 --port 8080
      ports:
        - '8080:8080'
      environment:
        VEC_MODEL_PATH: ${VEC_MODEL_PATH}
        MAX_WORKERS: ${MAX_WORKERS}
      volumes:
        - ./var/models:/opt/app/var/models/
